#' ---
#' title: RSV burden&cost calculations with incidence data from Kenya and South Africa 
#' author: Mihaly Koltai
#' date: 29/October 2020
#' ---
#' output:
#'    html_document:
#'      toc: true
#'      highlight: zenburn
#'      fig_width: 15
#'      fig_height: 10
#' ---
# Libraries
# to render as html: rmarkdown::render("RSV_kenya_SA_calculation.R",output_dir='output/cea_plots/')
rm(list=ls())
library(tidyverse); library(matrixStats); library(rstudioapi); library(fitdistrplus)
# sessionInfo()
# path
currentdir_path=dirname(rstudioapi::getSourceEditorContext()$path); setwd(currentdir_path)
# base MCMARCEL functions
source('functions/RSV_load_all.R')
# custom made functions
# from: http://www.medicine.mcgill.ca/epidemiology/Joseph/PBelisle/GammaParmsFromQuantiles.html
source('functions/GammaParmsFromQuantiles.R'); source('functions/get_burden_flexible.R'); source('functions/facet_wrap_fcns.R')
# run tag
run_tag <- 'RSV_gavi72_basecase'  # 72 Gavi countries (basecase) 
# number of stochastic samples in the probabilistic sensitivity analysis (PSA).
num_sim <- 5000
##### SELECT COUNTRY
cntrs_cea=c('KEN','ZAF'); n_cntr_output=1; cntr_sel=cntrs_cea[n_cntr_output]
# load config params
source('functions/load_config_pars.R')
# if running for many cntrs and we want to parallelise
# start_parallel_workers()
### Demographic data -------------------------
#' ## Load demographic data
#### Load life tables and incidence used by MCMARCEL (this is not needed for CEA below)
source('functions/load_incidence_lifetables.R')
# life_table %=% fcn_gen_lifetable(cntr_sel)[[2]]
# plot lifetable
fcn_plot_lifetable("ZAF",'')
# plot incidence for cntrs (Set argument to 'save' to save)
RSV_burden_Shi_2017_tidy <- fcn_get_RSV_burden_shi2017('input/RSV_burden_Shi_2017_tidy.csv')
fcn_plot_lmic_incidence(RSV_burden_Shi_2017_tidy,'')
### OWN BURDEN DATA --------------------------------------------------
#' ## Incidence data from partners (loads functions)
source('functions/load_own_data.R')
# hospitalisation rate in mcmarcel
kenya_hosp_rates_mcmarcel=as.numeric(
  get_rsv_ce_config(subset(sim_config_matrix,country_iso %in% "KEN" &intervention=="maternal"))$hosp_prob[1,])
### Kenya incidence data -------------------------
# hosp rate (p): p/(1-p) ~ norm
kenya_incid_hosp_rate=fcn_load_gen_samples_kenya(
  kenya_data_path="../path_rsv_data/SARI_Rates_2010_2018_updated/ARI_SARI_Rates_2010_2018_tidydata.csv",
  sel_disease="SARI",n_iter=5e3,age_maxval=60,CI95_const=1.96,CI_intervals=c(0.025,0.975),
  logit_hosp_rate_stdev=sd(log(kenya_hosp_rates_mcmarcel/(1-kenya_hosp_rates_mcmarcel))),n_length=1e3,x_prec=0.01,
  randsampl_distrib_type='gamma')
#' ### South Africa
s_afr_incid_hosp_rate=fcn_load_gen_samples_s_afr(safr_data_path="../path_rsv_data/s_afr_incidence_data.csv",
        s_afr_hosp_rates_filepath='input/safr_hosp_rate_province_means.csv',n_iter=5e3,age_maxval=60,CI95_const=1.96,
        CI_intervals=c(0.025,0.975),logit_hosp_rate_stdev=sd(log(kenya_hosp_rates_mcmarcel/(1-kenya_hosp_rates_mcmarcel))),
        n_length=1e3,x_prec=0.01,randsampl_distrib_type="gamma",popul_denom=1e5)
# plot distrib of hosp rates
# ggplot(data.frame(age=1, ken_value=kenya_incid_hosp_rate[[2]][1,], zaf_value=s_afr_incid_hosp_rate[[2]][1,]) %>%
#   pivot_longer(!age) %>% mutate(`logit(p_hosp)`=log(value/(1-value))) %>% rename(p_hosp=value) %>% 
#     pivot_longer(!c(age,name),names_to = "valtype") ) + facet_wrap(~valtype,scales="free") + 
#   geom_density(aes(x=value,group=name,color=factor(name))) + theme_bw() + standard_theme + xlab("") + 
#   theme(legend.position="bottom") + labs(color="") + ggtitle("hospitalisation probab")
# ggsave("output/sample_paths_test/hosp_rate_distrib.png",width = 15,height = 10,units = "cm")
### ### ### ### ### ### ### ### ### ### ### ### 
### new data vs generated by MCMARCEL
# community-based data (generated by MCMARCEL scripts)
kenya_s_afr_mcmarcel=bind_rows(lapply(c("KEN","ZAF"),function(x) {
  fcn_concat_incid_data(disease_categ=c("total","hospitalised"),
        list(get_rsv_ce_config(subset(sim_config_matrix,country_iso %in% x & intervention=="maternal"))$rsv_rate,
            get_rsv_ce_config(subset(sim_config_matrix,country_iso %in% x & intervention=="maternal"))$hosp_prob),cntrs=x)
  } ) ) %>% mutate(source="community-based (meta-analysis)") %>% mutate(country=ifelse(country=="KEN","Kenya","South Africa"))
# hospital-based (own) data
kenya_s_afr_own=bind_rows(fcn_concat_incid_data(disease_categ=c("total","hospitalised"),kenya_incid_hosp_rate,cntrs=c("Kenya")),
  fcn_concat_incid_data(disease_categ=c("total","hospitalised"),s_afr_incid_hosp_rate,cntrs=c("South Africa"))) %>% 
  mutate(source="hospital-based (surveillance data)")
# PLOT (countries and sources separate)
fcn_plot_compare_comm_hosp_data(kenya_s_afr_own,kenya_s_afr_mcmarcel,grouping_type="cntr")
# PLOT (countries and med categs separate)
# fcn_plot_compare_comm_hosp_data(kenya_s_afr_own,kenya_s_afr_mcmarcel,grouping_type="categ")
ggsave("output/comparison_mcmarcel_new_ZAF_KEN.png",width=30,height=18,units="cm")
### ### ### ### ### ### ### ### ### ### ### ###
# number of RSV cases expected
all_country_data <- data.frame(read_csv('./input/country_details_gavi72_expanded.csv'))
life_table_SA <- fcn_gen_lifetable("ZAF")[[2]]
config_SA_matvacc=get_rsv_ce_config(subset(sim_config_matrix,country_iso %in% "ZAF" & intervention=="maternal"))
under5popul_SA=subset(life_table_SA,age<=59)$lx_rate*(config_SA_matvacc$target_population*(1-config_SA_matvacc$stillbirth_rate))/12
sum(under5popul_SA*subset(kenya_s_afr_own,name %in% "hospitalised" & country %in% "South Africa")$mean)
sum(under5popul_SA*subset(kenya_s_afr_mcmarcel,name %in% "hospitalised" & country %in% "South Africa")$mean)
# Kenya
config_KEN_matvacc=get_rsv_ce_config(subset(sim_config_matrix,country_iso %in% "KEN" & intervention=="maternal"))
under5popul_KEN=subset(fcn_gen_lifetable("KEN")[[2]],age<=59)$lx_rate*(config_KEN_matvacc$target_population*(1-config_KEN_matvacc$stillbirth_rate))/12
sum(under5popul_KEN*subset(kenya_s_afr_own,name %in% "hospitalised" & country %in% "Kenya")$mean)
sum(under5popul_KEN*subset(kenya_s_afr_mcmarcel,name %in% "hospitalised" & country %in% "Kenya")$mean)
### ### ### ### ### ### ### ### ### ### ### ### 
# put all matrices into 1 list; 1 matrix: burden_list_own_data[[2]][[2]]
burden_list_own_data=list(kenya_incid_hosp_rate,s_afr_incid_hosp_rate)
### BURDEN & CEA CALCULATION --------------------------------------------------
#' ## BURDEN CALCULATION with OWN DATA
# South Africa was not in the original analysis, so we cannot compare to default mcmarcel output
# cntrs_cea=c('KEN','ZAF'); n_cntr_output=1
# read in config parameters for burden calculation
burden_cntr_ind=which(sim_config_matrix$country_iso %in% cntrs_cea[n_cntr_output])
# MV=sim_config_matrix[burden_cntr_ind[1],]; mAb=sim_config_matrix[burden_cntr_ind[2],]
# SELECT INTERVENTION: 1=MatVacc, 2=monocl Abs
n_interv=1; sel_interv=sim_config_matrix[burden_cntr_ind[n_interv],] # config <- get_rsv_ce_config(sel_interv)
if (n_cntr_output==2){sel_interv$country_iso=cntrs_cea[n_cntr_output]}
# with original MCMARCEL: # sim_output=get_burden(sel_interv)
####
# own data: need to provide incidence matrix [60*5e3] and hospitalisation matrix [60*5e3] as arguments
sim_output_user_input=get_burden_flexible(sel_interv,burden_list_own_data[[n_cntr_output]][[1]],
                                        burden_list_own_data[[n_cntr_output]][[2]])
# for original
sim_output=get_burden_flexible(sel_interv,NA,NA)
# check population times x rsv rate = rsv cases
# life_table$pop <- life_table$lx_rate * config$target_population_lifebirth / config$monthsInYear #fix 2018-01-11
# # with mcmarcel data: mean(colSums(life_table$pop[1:60]*config$rsv_rate ))
# # with our data: colSums(life_table$pop[1:60]*kenya_incid_hosp_rate[[1]])

### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 
### Plot results -------------------------
# outputs to display 
icercolname="incremental_cost/DALY_averted"
cols_burden_sel=c('rsv_cases_0to1y','hosp_cases_0to1y','rsv_deaths','total_DALY_disc',
  'cost_rsv_hosp_0to1y','total_medical_cost_0to1y','incremental_cost_disc','total_medical_cost_averted',
  "hosp_cases_averted", "rsv_deaths_averted", "total_DALY_disc_averted",icercolname) 
# "total_YLD_1to5y_averted","total_YLL_1to5y_averted",
# set xlimits by quantiles
source('functions/set_xlims_cea.R')
burden_mcmarcel_owndata=fcn_process_burden_output(sim_output_user_input,sim_output,sel_interv$country_iso,cols_burden_sel,
                          plot_labels=c(mcmarcel="community-based",own="hospital-based"),icercolname=icercolname,
                          icercols=c('incremental_cost_disc','total_DALY_disc_averted'))
# go to "CEA_distrib_plots.R" for plotting
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 
# mean values shown by vertical lines
color_vals=c('red','green'); mean_intercepts=fcn_mean_intercepts(burden_mcmarcel_owndata,color_vals)
quantl_vals=c(0.01,0.99); xlimvals=list(); xlimvals_cols=list()
# define xlims (leave xlimvals_cols, xlimvals)
quantls_min_max=fcn_calc_quantls_minmax(burden_mcmarcel_owndata,quantl_vals)
xmin_adj_vars=c('hosp_cases_0to1y'=0,'rsv_deaths'=-1e2,'total_DALY_disc'=-1e4,'cost_rsv_hosp_0to1y'=-1e3,
      'total_medical_cost_0to1y'=-1e6,'rsv_cases_0to1y'=0,'total_medical_cost_averted'=-1e6,'hosp_cases_averted'=-1e3,
      'rsv_deaths_averted'=-10,'total_DALY_disc_averted'=-2e3,"incremental_cost/DALY_averted"=-100) # ,'net_cost/DALY_averted'=-1e3
xmax_adj_vars=c('incremental_cost_disc',icercolname); icer_maxval=3e3; scale_max_val=2
# leave last argument empty for automatic x limits
scales_list=fcn_set_xlims(sel_interv$country_iso,burden_mcmarcel_owndata,quantls_min_max,xmin_adj_vars,
                          xmax_adj_vars,icer_maxval,scale_max_val,'man_adj_flag')
# manually adjust
l_man_adj=list("cost_rsv_hosp_0to1y"=c(0,4.5e6),"hosp_cases_0to1y"=c(0,2.5e4),"hosp_cases_averted"=c(0,7e3),
          "hosp_cases_averted"=c(0,7e3),"incremental_cost_disc"=c(1.8e6,4e6),"rsv_cases_0to1y"=c(2e4,2e5),"rsv_deaths"=c(0,2e3),
          "total_medical_cost_averted"=c(0,2e6),"incremental_cost/DALY_averted"=c(-1e2,5e3),"total_DALY_disc"=c(0,6e4))
sapply(1:length(l_man_adj), function(x) {
  scales_list[[which(sort(cols_burden_sel) %in% names(l_man_adj)[x])]]$scale$limits=l_man_adj[[x]]})
### Plot CEA histograms ------------------
if (n_interv==1) {interv_tag='_Mat_Vacc' } else {interv_tag='_monocl_Ab'}
ggplot(burden_mcmarcel_owndata,aes(x=value,group=source)) + geom_freqpoly(aes(color=source),size=1.2) + 
  geom_vline(data=mean_intercepts,aes(xintercept=int,linetype=source),size=0.8) + # binwidth=max(value)/100,bins=20
  # facet_wrap(~variable,scales='free',labeller=label_wrap_gen(width=10)) + #geom_text(aes(x=mean(value),y=100,label=mean(value))) +
  facet_wrap_custom(~variable,scales='free',scale_overrides=scales_list,labeller=label_wrap_gen(width=10)) +
  theme_bw() + standard_theme + scale_linetype_manual(values=c('solid','dotdash')) + # theme(legend.position="bottom") +
  geom_rect(data=subset(burden_mcmarcel_owndata, variable %in% icercolname),fill=NA,colour="blue",
            size=2,xmin=-Inf,xmax=Inf,ymin=-Inf,ymax=Inf) + scale_x_continuous(expand=expansion(0,0)) + 
  ggtitle(paste(sel_interv$country_iso,'RSV burden & intervention estimates:',gsub('_','',interv_tag))) + xlab("") +
  labs(color="",linetype="") # + guides(xintercept=FALSE,linetype=guide_legend(nrow=2,byrow=TRUE))
# save plot
calc_tag="_nonhospSARIasmild" # "calc_tag"
cea_plot_filename=paste("output/cea_plots/",sel_interv$country_iso,"_mcmarcel_burden_estimates_n",5000,
                        interv_tag,'_',"gamma_samples",calc_tag,".png",sep="")
# if (!dir.exists('output/cea_plots')) {dir.create('output/cea_plots')}
# SAVE
ggsave(cea_plot_filename,width=30,height=18,units="cm")
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 
### plot CFR by age
hosp_CFR=data.frame(age=1:60,CFR_mean=rowMeans(config_KEN_matvacc$hosp_CFR)*1e2,
  t(sapply(1:60, function(x) {as.numeric(quantile(config_KEN_matvacc$hosp_CFR[x,],probs=c(2.5,97.5)/1e2))*1e2}))) %>% 
  rename(CI95_lower=X1,CI95_upper=X2)
ggplot(hosp_CFR,aes(x=age)) + geom_line(aes(y=CFR_mean)) + geom_point(aes(y=CFR_mean)) + 
  geom_ribbon(aes(ymin=CI95_lower,ymax=CI95_upper),alpha=0.1) + theme_bw() + scale_y_continuous(breaks = (0:14)/2) +
  standard_theme + scale_x_continuous(breaks = 1:60,expand = expansion(0.01,0)) + ylab("hospital CFR (%)")
ggsave("output/hospital_CFR.png",width=30,height=18,units="cm")

### Net cost/DALY averted (mean, median, stdev) -------------------------
cea_csv_filename=gsub('.png','.csv',cea_plot_filename)
cea_summary=burden_mcmarcel_owndata %>% group_by(source,variable) %>% 
  summarise(meanvals=mean(value),medianval=median(value),stdevvals=sd(value))
# take the ratio of means, not vice versa
for (mean_med in c("meanvals","medianval")) {cea_summary[cea_summary$variable %in% "net_cost/DALY_averted",mean_med]=cea_summary[cea_summary$variable %in% "incremental_cost_0to1y",mean_med]/
  cea_summary[cea_summary$variable %in% "total_DALY_0to1y_averted",mean_med] }
write_csv(cea_summary,cea_csv_filename)

### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
### Extrapolation to other Sub-Sah Afr countries -------------------------
# fraction of cases by age groups
kenya_agegroup_fractions=rowMeans(kenya_incid_hosp_rate[[1]]/colSums(kenya_incid_hosp_rate[[1]]))
if (!sum(kenya_agegroup_fractions)==1){kenya_agegroup_fractions=kenya_agegroup_fractions/sum(kenya_agegroup_fractions)}
# S Afr
s_afr_agegroup_fractions=rowMeans(s_afr_incid_hosp_rate[[1]]/colSums(s_afr_incid_hosp_rate[[1]]))
if (!sum(s_afr_agegroup_fractions)==1){s_afr_agegroup_fractions=s_afr_agegroup_fractions/sum(s_afr_agegroup_fractions)}
# SELECT AGE DISTRIBUTION
n_age_distrib=1; age_distrib_used=c('KEN','ZAF')[n_age_distrib]; age_distrib_names=c('kenya_age_distrib','s_afr_age_distrib')
# SELECT FOLDER TO SAVE/WRITE FILES TO
if (age_distrib_used %in% 'ZAF') {
  agegroup_fractions=s_afr_agegroup_fractions; folder_projection='output/sub_sah_afr_proj/s_afr_age_distrib/' } else {
    agegroup_fractions=kenya_agegroup_fractions; folder_projection='output/sub_sah_afr_proj/kenya_age_distrib/' }
# mean incidence
RSV_burden_Shi_2017=read_csv('input/RSV_burden_Shi_2017.csv')
# sub-Saharan Afr countries
sub_sah_afr_cntrs=c("Angola","Benin","Botswana","Burkina Faso","Burundi","Cameroon","Cape Verde","Central African Republic",
"Chad","Comoros","Congo, Rep.","Congo, Dem. Rep.","C_te d'Ivoire","Djibouti","Equatorial Guinea","Eritrea","Ethiopia","Gabon",
"Gambia, The","Ghana","Guinea","Guinea-Bissau","Kenya","Lesotho","Liberia","Madagascar","Malawi","Mali","Mauritania","Mauritius",
"Mozambique","Namibia","Niger","Nigeria","Rwanda","S_o Tom_ and Principe","Senegal","Seychelles","Sierra Leone","Somalia",
"South Africa","Sudan","South Sudan","Swaziland","Tanzania","Togo","Uganda","Zambia","Zimbabwe")
# convert to ISO3
sub_sah_afr_cntrs_iso3=RSV_burden_Shi_2017$country_iso[RSV_burden_Shi_2017$location_name %in% sub_sah_afr_cntrs]
sub_sah_afr_cntrs_iso3=sub_sah_afr_cntrs_iso3[sub_sah_afr_cntrs_iso3 %in% sim_config_matrix$country_iso]
# which intervention?
n_interv=2; interv_tags_list=c('mat_vacc','monocl_Ab'); interv_tag=interv_tags_list[n_interv]
### Calculate CEA  -------------------------
set.seed(as.integer(format(Sys.Date(), "%Y%m%d")))
start_parallel_workers(); all_packages=append(all_packages,'readr')
### 
# this is time consuming, ~30mins depending on # CPUs
# ptm <- proc.time()
foreach(k=1:length(sub_sah_afr_cntrs_iso3),.combine='rbind',.packages=all_packages,.verbose=FALSE) %dopar% {
  # LOOP through SubSah cntrs
  cntr_name=sub_sah_afr_cntrs_iso3[k]; df_country <- get_incidence(cntr_name,output_dir)
  # Set config values
  config=list(); config$rsv_rate <- df_country[[1]]; config$hosp_prob <- df_country[[2]]; config$hosp_CFR <- df_country[[3]]
  rsv_rate_fractions=sapply(1:ncol(config$rsv_rate),function(x) {config$rsv_rate[,x]/sum(config$rsv_rate[,x])})
  subsah_incid_redist=matrix(unlist(lapply(colSums(config$rsv_rate),function(x) {agegroup_fractions*x})),ncol=n_iter)
  # can generate values x>1 or x<0: 
# sapply(1:n_iter, function(x){ (rsv_rate_fractions[,x]/rowMeans(rsv_rate_fractions))*agegroup_fractions*sum(config$rsv_rate[,x]) })
# generates low noise: matrix(unlist(lapply(colSums(config$rsv_rate),function(x) {agegroup_fractions*x})),ncol=n_iter)
  sel_interv=sim_config_matrix[which(sim_config_matrix$country_iso %in% cntr_name)[n_interv],] 
  if (!is.na(sel_interv$rng_seed)){ 
    write_csv(get_burden_flexible(sel_interv,subsah_incid_redist,config$hosp_prob),
            paste0(paste0(folder_projection,interv_tag,"/"),cntr_name,"_own_data.csv"))
    print(paste("done with",cntr_name,"own data",sep=" ")) # mcmarcel_outputs=get_burden_flexible(sel_interv,NA,NA)}
    write_csv(get_burden_flexible(sel_interv,NA,NA), paste0(paste0(folder_projection,interv_tag,"/"),cntr_name,"_mcmarcel.csv")) }
}
# proc.time() - ptm

#### Process extrapolation results  -------------------------
# select datafiles
# folder_projection="output/sub_sah_afr_proj/kenya_age_distrib/" # "output/sub_sah_afr_proj/s_afr_age_distrib/"
# check if input and output folders are aligned
if (grepl(folder_projection,paste0(folder_projection,interv_tag,"/"))) {print('folders OK.')} else {
  paste0(folder_projection,interv_tag,"/")=paste0(folder_projection,interv_tag,"/") }
cea_file_list=list.files(paste0(folder_projection,'/',interv_tag)); cea_file_list=cea_file_list[grepl('.csv',cea_file_list)]
cea_file_id=sapply(strsplit(cea_file_list,"_"),'[[',1); burden_comparison_all_subsah_afr=list()
# x axis limits
icercolname="net_cost/DALY_averted"; cols_burden_sel=c('rsv_cases','hosp_cases','rsv_deaths','total_DALY_0to1y',
              'cost_rsv_hosp_0to1y','total_medical_cost_0to1y','incremental_cost_0to1y','total_medical_cost_averted',
              "hosp_cases_averted", "rsv_deaths_averted", "total_DALY_0to1y_averted",icercolname)
xmin_adj_vars=c('rsv_cases','hosp_cases','rsv_deaths','total_DALY_0to1y','cost_rsv_hosp_0to1y','total_medical_cost_0to1y',
  'total_medical_cost_averted','hosp_cases_averted','rsv_deaths_averted','total_DALY_0to1y_averted','net_cost/DALY_averted')
xmax_adj_vars=c('rsv_cases','incremental_cost_0to1y','net_cost/DALY_averted')
# PLOT CONFIG
# quantile to draw x-axis limits
quantl_vals=c(0.01,0.99); color_vals=c('red','green')
# quantiles to store in csv file
quantl_vals_90=c(0.05,0.9)
# minvals for x-axis, maxval for ICER, scaling of maxvals of x-axis
source('functions/set_xlims_cea.R')
xmin_adj_values=c(0,0,-1e2,-1e3,-1e6,-1e6,-1e6,-1e3,-10,-2e3,-1e3); icer_maxval=3e3; scale_max_val=2
save_flag='save'; list_all_subsah_afr=list()
for (k in 1:length(sub_sah_afr_cntrs_iso3)){
  sel_cntr=sub_sah_afr_cntrs_iso3[k]; CEA_files_indcntr=cea_file_list[cea_file_id %in% sel_cntr]
  sel_cntr_fullname=RSV_burden_Shi_2017$location_name[RSV_burden_Shi_2017$country_iso %in% sel_cntr]
  # own data will be always the 2nd of the two files for each country
  burden_mcmarcel_owndata=fcn_process_burden_output(
    read_csv( paste0(paste0(folder_projection,interv_tag,"/"),CEA_files_indcntr[[2]]) ), 
    read_csv( paste0(paste0(folder_projection,interv_tag,"/"),CEA_files_indcntr[[1]]) ), sel_cntr,cols_burden_sel)
  # PLOT distribution (density plot)
  data_to_plot=burden_mcmarcel_owndata; data_to_plot$source=gsub(' ','',gsub("\\(|\\)","",gsub(sel_cntr,"",data_to_plot$source)))
  ## we'll show mean values by vertical lines
  mean_intercepts=fcn_mean_intercepts(data_to_plot,color_vals)
  # set xlimits by quantiles
  quantls_min_max=fcn_calc_quantls_minmax(burden_mcmarcel_owndata,quantl_vals)
  # leave last argument empty for automatic x limits
  scales_list=fcn_set_xlims(sel_cntr,burden_mcmarcel_owndata_comp,quantls_min_max,xmin_adj_vars,xmin_adj_values,
               xmax_adj_vars,icer_maxval,scale_max_val,'man_adj_flag')
  # leave 'scales_list' empty to have default x axes
  # PLOT distributions of variables for selected country
  if (!dir.exists(paste0(paste0(folder_projection,interv_tag,"/"),'plots/'))) {
    dir.create(paste0(paste0(folder_projection,interv_tag,"/"),'plots/'))}
  fcn_plot_cea_distribs(data_to_plot,mean_intercepts,scales_list,standard_theme,n_interv, # scales_list
              sel_cntr_fullname,paste0(paste0(folder_projection,interv_tag,"/"),'plots/'),save_flag)
 ## WRITE TABLE WITH mean/median/stdev + QUINTILES
 list_all_subsah_afr[[k]]=fcn_burden_median_mean(burden_mcmarcel_owndata)
}

burden_comparison_all_subsah_afr=fcn_process_median_burden(list_all_subsah_afr,interv_tag)
burden_summary_filename=paste0(folder_projection,'burden_comparison_all_subsah_afr_',interv_tag,'.csv')
write_csv(burden_comparison_all_subsah_afr,burden_summary_filename)

### combine two tables with diff age distributions (same intervention) --------------------
if (length(unique(burden_comparison_all_subsah_afr$age_distrib))==1){
burden_comparison_all_subsah_afr=rbind(read_csv(burden_summary_filename),
  read_csv(gsub(age_distrib_names[n_age_distrib],age_distrib_names[setdiff(c(1:2),n_age_distrib)],burden_summary_filename)))}
filename_combined_agedistr_interv=paste0('output/sub_sah_afr_proj/burden_comparison_all_subsah_afr_',interv_tag,'.csv')
if (!file.exists(filename_combined_agedistr_interv)) {write_csv(burden_comparison_all_subsah_afr,filename_combined_agedistr_interv)}

# read in results using both age distribs
# burden_comparison_all_subsah_afr=read_csv(filename_combined_agedistr_interv)
# the results from two cntrs with mcmarcel age distrib have to be the same, removing one of them
mcmarcel_agedistrib_dupl_rows=burden_comparison_all_subsah_afr$source %in% 'mcmarcel' & burden_comparison_all_subsah_afr$age_distrib %in% "KEN"
burden_comparison_all_subsah_afr=burden_comparison_all_subsah_afr[!mcmarcel_agedistrib_dupl_rows,]
burden_comparison_all_subsah_afr$age_distrib[burden_comparison_all_subsah_afr$source %in% 'mcmarcel']='Shi2017'
# set order by factoring
burden_comparison_all_subsah_afr$variable=factor(burden_comparison_all_subsah_afr$variable,levels = cols_burden_sel)
burden_comparison_all_subsah_afr$age_distrib=factor(burden_comparison_all_subsah_afr$age_distrib,levels=c("Shi2017","ZAF","KEN"))
# filter out cntrs below X million
# using "wpp2019" and "countrycode": 
# library(wpp2019); library(countrycode); data("pop")
sub_sah_afr_cntrs_popul2020=pop[pop$country_code %in% countrycode(sub_sah_afr_cntrs_iso3,origin='iso3c',destination='iso3n'),"2020"]
cntr_list=popproj[popproj$country_code %in% countrycode(sub_sah_afr_cntrs_iso3,origin='iso3c',destination='iso3n'),"name"]
# data.frame(cntrs=cntr_list,popul=sub_sah_afr_cntrs_popul2020)
# cntrs with popul larger than 5 million
cntr_list_popul_lt=countrycode(cntr_list,origin='country.name',destination='iso3c')[sub_sah_afr_cntrs_popul2020>5e3]

# plot all countries together
burden_vars=cols_burden_sel[1:6]; interv_vars=cols_burden_sel[7:length(cols_burden_sel)]
# select vars to plot
varselect=burden_comparison_all_subsah_afr$country %in% cntr_list_popul_lt & 
  (burden_comparison_all_subsah_afr$variable %in% interv_vars)
#
ggplot(burden_comparison_all_subsah_afr[varselect,],aes(x=country,y=medianval,ymin=min_q,ymax=max_q)) + # medianval-stdevvals
 geom_pointrange(aes(color=age_distrib,shape=age_distrib,linetype=age_distrib),
                 fatten=1.8,size=0.8,position=position_dodge(width=0.6)) +
  facet_wrap(~variable,scales='free',ncol=2) + scale_color_manual(values=c('blue','red2','red3')) +
  scale_linetype_manual(values=c('twodash','solid','solid')) + theme_bw() + standard_theme + theme(legend.key.size = grid::unit(3, "lines")) + 
  labs(color='data source',shape='data source',linetype='data source') + # guides(linetype=FALSE) +
  xlab('') + ylab('') + ggtitle('Effect of age distribution on projected CEA')
# guide_legend(override.aes=list(shape=NA)),color=FALSE
####
# save
if (any(burden_comparison_all_subsah_afr$variable[varselect] %in% interv_vars)) {
  ggsave(paste0('output/sub_sah_afr_proj/summary_plots/intervention_variable_faceted_',interv_tag,'.png'),
         width=50,height=30,units="cm")
} else {
  ggsave(paste0('output/sub_sah_afr_proj/summary_plots/burden_variable_faceted_',interv_tag,'.png'),width=50,height=30,units="cm")
}
